using MailKit.Net.Smtp;
using Microsoft.Extensions.Configuration;
using MimeKit;
using System;
using System.Text;
using Taxi.Common.Enums;
using Taxi.Common.Models;

namespace Taxi.Web.Helpers
{
    public class MailHelper : IMailHelper
    {
        private readonly IConfiguration _configuration;

        public MailHelper(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public Response SendMail(string to, string subject, string body)
        {
            try
            {
                string from = _configuration["Mail:From"];
                string smtp = _configuration["Mail:Smtp"];
                string port = _configuration["Mail:Port"];
                string password = _configuration["Mail:Password"];

                MimeMessage message = new MimeMessage();
                message.From.Add(new MailboxAddress(from));
                message.To.Add(new MailboxAddress(to));
                message.Subject = subject;
                BodyBuilder bodyBuilder = new BodyBuilder
                {
                    HtmlBody = body
                };
                message.Body = bodyBuilder.ToMessageBody();

                using (SmtpClient client = new SmtpClient())
                {
                    client.Connect(smtp, int.Parse(port), true);
                    client.Authenticate(from, password);
                    client.Send(message);
                    client.Disconnect(true);
                }

                return new Response { IsSuccess = true };

            }
            catch (Exception ex)
            {
                return new Response
                {
                    IsSuccess = false,
                    Message = ex.Message,
                    Result = ex
                };
            }
        }

        public string CreateBody(MailBody typeMail, string UserName, string url)
        {
            StringBuilder body = new StringBuilder();
            switch (typeMail)
            {
                case MailBody.Activation:
                    body.Append("<!doctype html><html xmlns = \"http://www.w3.org/1999/xhtml\" xmlns: v = \"urn:schemas-microsoft-com:vml\" xmlns: o = \"urn:schemas-microsoft-com:office:office\">");
                    body.AppendLine("<head><title></ title>");
                    body.AppendLine("<!--[if !mso]><!---->");
                    body.AppendLine("<meta http - equiv = \"X-UA-Compatible\" content = \"IE=edge\">");
                    body.AppendLine("<!--<![endif]-->");
                    body.AppendLine("<meta http - equiv = \"Content-Type\" content = \"text/html; charset=UTF-8\">");
                    body.AppendLine("<meta name = \"viewport\" content = \"width=device-width, initial-scale=1\">");
                    body.AppendLine("<style type = \"text/css\">");
                    body.AppendLine("# outlook a {");
                    body.AppendLine("padding: 0;");
                    body.AppendLine("}");
                    body.AppendLine(".ReadMsgBody {");
                    body.AppendLine("width: 100 %;");
                    body.AppendLine("}");
                    body.AppendLine(".ExternalClass {");
                    body.AppendLine("width: 100 %;");
                    body.AppendLine("}");
                    body.AppendLine(".ExternalClass * {");
                    body.AppendLine("line - height: 100 %;");
                    body.AppendLine("}");
                    body.AppendLine("body {");
                    body.AppendLine("margin: 0;");
                    body.AppendLine("padding: 0;");
                    body.AppendLine("- webkit - text - size - adjust: 100 %;");
                    body.AppendLine("- ms - text - size - adjust: 100 %;");
                    body.AppendLine("}");
                    body.AppendLine("table,");
                    body.AppendLine("td {");
                    body.AppendLine("border - collapse: collapse;");
                    body.AppendLine("mso - table - lspace: 0pt;");
                    body.AppendLine("mso - table - rspace: 0pt;");
                    body.AppendLine("}");
                    body.AppendLine("img {");
                    body.AppendLine("border: 0;");
                    body.AppendLine("height: auto;");
                    body.AppendLine("line - height: 100 %;");
                    body.AppendLine("outline: none;");
                    body.AppendLine("text - decoration: none;");
                    body.AppendLine("- ms - interpolation - mode: bicubic;");
                    body.AppendLine("}");
                    body.AppendLine("p {");
                    body.AppendLine("display: block;");
                    body.AppendLine("margin: 13px 0;");
                    body.AppendLine("}");
                    body.AppendLine("</style>");
                    body.AppendLine("<!--[if !mso]><!-->");
                    body.AppendLine("<style type = \"text/css\">");
                    body.AppendLine("@media only screen and(max - width:480px) {");
                    body.AppendLine("@-ms - viewport {");
                    body.AppendLine("width: 320px;");
                    body.AppendLine("}");
                    body.AppendLine("@viewport {");
                    body.AppendLine("width: 320px;");
                    body.AppendLine("}");
                    body.AppendLine("}");
                    body.AppendLine("</style>");
                    body.AppendLine("<!--<![endif]-->");
                    body.AppendLine("<!--[if mso]>");
                    body.AppendLine("<xml>");
                    body.AppendLine("<o:OfficeDocumentSettings>");
                    body.AppendLine("<o:AllowPNG/>");
                    body.AppendLine("<o:PixelsPerInch> 96 </ o:PixelsPerInch>");
                    body.AppendLine("</o:OfficeDocumentSettings>");
                    body.AppendLine("</xml>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<!--[if lte mso 11]>");
                    body.AppendLine("<style type = \"text/css\">");
                    body.AppendLine(".outlook - group - fix { width: 100 % !important; }");
                    body.AppendLine("</style>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<!--[if !mso]><!-->");
                    body.AppendLine("<link href = \"https://fonts.googleapis.com/css?family=Open Sans\" rel = \"stylesheet\" type = \"text/css\">");
                    body.AppendLine("<style type = \"text/css\">");
                    body.AppendLine("@import url(https://fonts.googleapis.com/css?family=Open Sans);");
                    body.AppendLine("</style>");
                    body.AppendLine("<!--<![endif]-->");
                    body.AppendLine("<style type = \"text/css\">");
                    body.AppendLine("@media only screen and(min - width:480px) {");
                    body.AppendLine(".mj - column - per - 100 {");
                    body.AppendLine("width: 100 % !important;");
                    body.AppendLine("max - width: 100 %;");
                    body.AppendLine("}");
                    body.AppendLine("}");
                    body.AppendLine("</style>");
                    body.AppendLine("<style type = \"text/css\">");
                    body.AppendLine("[owa].mj - column - per - 100 {");
                    body.AppendLine("width: 100 % !important;");
                    body.AppendLine("max - width: 100 %;");
                    body.AppendLine("}");
                    body.AppendLine("</style>");
                    body.AppendLine("<style type = \"text/css\">");
                    body.AppendLine("@media only screen and(max - width:480px) {");
                    body.AppendLine("table.full - width - mobile {");
                    body.AppendLine("width: 100 % !important;");
                    body.AppendLine("}");
                    body.AppendLine("td.full - width - mobile {");
                    body.AppendLine("width: auto!important;");
                    body.AppendLine("}");
                    body.AppendLine("}");
                    body.AppendLine("</style>");
                    body.AppendLine("</head>");
                    body.AppendLine("<body style = \"background-color:#f8f8f8;\">");
                    body.AppendLine("<div style = \"background-color:#f8f8f8;\">");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table");
                    body.AppendLine("align = \"center\" border = \"0\" cellpadding = \"0\" cellspacing = \"0\" class=\"\" style=\"width:600px;\" width=\"600\"");
                    body.AppendLine(">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div style=\"Margin:0px auto;max-width:600px;\">");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">");
                    body.AppendLine("<tbody>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"direction:ltr;font-size:0px;padding:20px 0px 20px 0px;padding-bottom:0px;padding-top:0px;text-align:center;vertical-align:top;\">");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td");
                    body.AppendLine("class=\"\" style=\"vertical-align:top;width:600px;\"");
                    body.AppendLine(">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"left\" style=\"font-size:0px;padding:0px 0px 0px 25px;padding-top:0px;padding-bottom:0px;word-break:break-word;\">");
                    body.AppendLine("<div style = \"font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:11px;line-height:22px;text-align:left;color:#797e82;\">");
                    body.AppendLine("<p style=\"text-align: center; margin: 10px 0;\">Lorem ipsum dolor sit&nbsp;| <a target = \"_blank\" rel=\"noopener noreferrer\" href=\"#\"></a><span style = \"color:#797e82; text-decoration: underline\"> View online version</span></p>");
                    body.AppendLine("</div>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</tbody>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<table");
                    body.AppendLine("align = \"center\" border= \"0\" cellpadding= \"0\" cellspacing= \"0\" class=\"\" style=\"width:600px;\" width=\"600\"");
                    body.AppendLine(">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div style=\"background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;\">");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#ffffff;background-color:#ffffff;width:100%;\">");
                    body.AppendLine("<tbody>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"direction:ltr;font-size:0px;padding:20px 0;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-align:center;vertical-align:top;\">");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td");
                    body.AppendLine("class=\"\" style=\"vertical-align:top;width:600px;\"");
                    body.AppendLine(">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"font-size:0px;padding:10px 25px;padding-top:0px;padding-right:0px;padding-bottom:40px;padding-left:0px;word-break:break-word;\">");
                    body.AppendLine("<p style=\"border-top:solid 7px #1F557F;font-size:1;margin:0px auto;width:100%;\">");
                    body.AppendLine("</p>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table");
                    body.AppendLine("align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-top:solid 7px #1F557F;font-size:1;margin:0px auto;width:600px;\" role=\"presentation\" width=\"600px\"");
                    body.AppendLine(">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"height:0;line-height:0;\">");
                    body.AppendLine("&nbsp;");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"center\" style=\"font-size:0px;padding:10px 25px;padding-top:0px;padding-bottom:0px;word-break:break-word;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">");
                    body.AppendLine("<tbody>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"width:110px;\">");
                    body.AppendLine("<img alt=\"\" height=\"auto\" src=\"https://img.icons8.com/cotton/64/000000/taxi-service.png\" style=\"border:none;display:block;outline:none;text-decoration:none;height:auto;width:100%;\" title=\"\" width=\"110\"/>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</tbody>");
                    body.AppendLine("</table>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</tbody>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<table");
                    body.AppendLine("align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"");
                    body.AppendLine(">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div style=\"background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;\">");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#ffffff;background-color:#ffffff;width:100%;\">");
                    body.AppendLine("<tbody>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"direction:ltr;font-size:0px;padding:20px 0;padding-bottom:0px;padding-top:0px;text-align:center;vertical-align:top;\">");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td");
                    body.AppendLine("class=\"\" style=\"vertical-align:top;width:600px;\"");
                    body.AppendLine(">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"center\" style=\"font-size:0px;padding:10px 25px;padding-top:40px;padding-right:50px;padding-bottom:0px;padding-left:50px;word-break:break-word;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">");
                    body.AppendLine("<tbody>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"width:300px;\">");
                    body.AppendLine("<img alt=\"\" height=\"auto\" src=\"http://9pl9.mjt.lu/tplimg/9pl9/b/ygjj/t65lu.png\" style=\"border:none;display:block;outline:none;text-decoration:none;height:auto;width:100%;\" title=\"\" width=\"300\"/>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</tbody>");
                    body.AppendLine("</table>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</tbody>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<table");
                    body.AppendLine("align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" style=\"width:600px;\" width=\"600\"");
                    body.AppendLine(">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div style=\"background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;\">");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#ffffff;background-color:#ffffff;width:100%;\">");
                    body.AppendLine("<tbody>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"direction:ltr;font-size:0px;padding:20px 0px 20px 0px;padding-bottom:70px;padding-top:30px;text-align:center;vertical-align:top;\">");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td");
                    body.AppendLine("class=\"\" style=\"vertical-align:top;width:600px;\"");
                    body.AppendLine(">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"left\" style=\"font-size:0px;padding:0px 25px 0px 25px;padding-top:0px;padding-right:50px;padding-bottom:0px;padding-left:50px;word-break:break-word;\">");
                    body.AppendLine("<div style = \"font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;text-align:left;color:#797e82;\">");
                    body.AppendLine("<h1 style=\"text-align:center; color: #000000; line-height:32px\">You&apos;re almost there!</h1>");
                    body.AppendLine("</div>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"left\" style=\"font-size:0px;padding:0px 25px 0px 25px;padding-top:0px;padding-right:50px;padding-bottom:0px;padding-left:50px;word-break:break-word;\">");
                    body.AppendLine("<div style = \"font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;text-align:left;color:#797e82;\">");
                    body.AppendFormat("<p style=\"margin: 10px 0; text-align: center;\">Hi {0}, Thank you for signing up to TaxiApp.&nbsp;</p>", UserName);
                    body.AppendLine("<p style = \"margin: 10px 0; text-align: center;\"> To confirm your account, simply click on the button below:</p>");
                    body.AppendLine("</div>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"center\" vertical-align=\"middle\" style=\"font-size:0px;padding:10px 25px;padding-top:20px;padding-bottom:20px;word-break:break-word;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"center\" bgcolor=\"#1F557F\" role=\"presentation\" style=\"border:none;border-radius:100px;cursor:auto;padding:15px 25px 15px 25px;background:#1F557F;\" valign=\"middle\">");
                    body.AppendFormat("<a href = \"{0}\" style=\"background:#1F557F;color:#ffffff;font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;Margin:0;text-decoration:none;text-transform:none;\" target=\"_blank\">", url);
                    body.AppendLine("<b style = \"font-weight:700\"><b style=\"font-weight:700\">Activate My Account</b></b>");
                    body.AppendLine("</a>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"left\" style=\"font-size:0px;padding:0px 25px 0px 25px;padding-top:0px;padding-right:50px;padding-bottom:0px;padding-left:50px;word-break:break-word;\">");
                    body.AppendLine("<div style = \"font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;text-align:left;color:#797e82;\">");
                    body.AppendFormat("<p style=\"margin: 10px 0; text-align: center;\">If the link doesn&rsquo;t work, copy this URL into your browser: <a target = \"_blank\" rel=\"noopener noreferrer\" href=\"{0}\" style=\"color:#1F557F\">{0}</a></p>", url);
                    body.AppendLine("<p style = \"margin: 10px 0; text-align: center;\"><i style= \"font-style:normal\"><b style= \"font-weight:700\"> Welcome! </ b></ i></ p>");
                    body.AppendLine("</div>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]> ");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</tbody>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<table");
                    body.AppendLine("align = \"center\" border= \"0\" cellpadding= \"0\" cellspacing= \"0\" class=\"\" style=\"width:600px;\" width=\"600\"");
                    body.AppendLine(">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div style=\"Margin:0px auto;max-width:600px;\">");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">");
                    body.AppendLine("<tbody>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"direction:ltr;font-size:0px;padding:20px 0px 20px 0px;padding-bottom:0px;padding-top:20px;text-align:center;vertical-align:top;\">");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td");
                    body.AppendLine("class=\"\" style=\"vertical-align:top;width:600px;\"");
                    body.AppendLine(">");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">");
                    body.AppendLine("<table border = \"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"center\" style=\"font-size:0px;padding:10px 25px;padding-bottom:0px;word-break:break-word;\">");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("<table");
                    body.AppendLine("align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"");
                    body.AppendLine(">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"float:none;display:inline-table;\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"padding:4px;\">");
                    body.AppendLine("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#1F557F;border-radius:6px;width:30;\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"font-size:0;height:30;vertical-align:middle;width:30;\">");
                    body.AppendLine("<a href=\"https://www.facebook.com/vladimiranda/\" target=\"_blank\">");
                    body.AppendLine("<img height = \"30\" src=\"http://www.mailjet.com/saas-templates-creator/static/img/facebook_white.png\" style=\"border-radius:6px;\" width=\"30\"/>");
                    body.AppendLine("</a>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("<td>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"float:none;display:inline-table;\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"padding:4px;\">");
                    body.AppendLine("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#1F557F;border-radius:6px;width:30;\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"font-size:0;height:30;vertical-align:middle;width:30;\">");
                    body.AppendLine("<a href=\"[[SHORT_PERMALINK]]\" target=\"_blank\">");
                    body.AppendLine("<img height = \"30\" src=\"http://www.mailjet.com/saas-templates-creator/static/img/twitter_white.png\" style=\"border-radius:6px;\" width=\"30\"/>");
                    body.AppendLine("</a>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("<td>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("<table align = \"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"float:none;display:inline-table;\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"padding:4px;\">");
                    body.AppendLine("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#1F557F;border-radius:6px;width:30;\">");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td style = \"font-size:0;height:30;vertical-align:middle;width:30;\">");
                    body.AppendLine("<a href=\"[[SHORT_PERMALINK]]\" target=\"_blank\">");
                    body.AppendLine("<img height = \"30\" src=\"http://www.mailjet.com/saas-templates-creator/static/img/linkedin_white.png\" style=\"border-radius:6px;\" width=\"30\"/>");
                    body.AppendLine("</a>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("<tr>");
                    body.AppendLine("<td align = \"center\" style=\"font-size:0px;padding:0px 20px 0px 20px;padding-top:0px;padding-bottom:0px;word-break:break-word;\">");
                    body.AppendLine("<div style = \"font-family:Open Sans, Helvetica, Arial, sans-serif;font-size:11px;line-height:22px;text-align:center;color:#797e82;\">");
                    body.AppendLine("<p style=\"margin: 10px 0;\"><a target = \"_blank\" rel=\"noopener noreferrer\" style=\"color:#1F557F\" href=\"#\"><span style = \"color:#1F557F\"> Page 1</span></a><span style = \"color:#797e82\"> &nbsp; &nbsp;|&nbsp; &nbsp;</span><a target = \"_blank\" rel=\"noopener noreferrer\" style=\"color:#1F557F\" href=\"#\"><span style = \"color:#1F557F\"> Page 2</span></a><span style = \"color:#797e82\"> &nbsp; &nbsp;|&nbsp; &nbsp;</span><a target = \"_blank\" rel=\"noopener noreferrer\" style=\"color:#1F557F\" href=\"#\"><span style = \"color:#1F557F\"> Page 3</span></a></p>");
                    body.AppendLine("<p style = \"margin: 10px 0;\"> C <a target=\"_blank\" rel=\"noopener noreferrer\" style=\"color:inherit; text-decoration:none\" href=\"[[UNSUB_LINK_EN]]\">lick<span style=\"color:#1F557F\"><u>here</u></span> to unsubscribe</a>.<br/><span style = \"font-size:10px\"> Created by&nbsp;</span><a target = \"_blank\" rel=\"noopener noreferrer\" style=\"font-size:10px; color:inherit; text-decoration: none\" href=\"https://www.mailjet.com/?utm_source=saas_email_templates&amp;utm_medium=logo_footer_email&amp;utm_campaign=account_activation\"><span style = \"color:#1F557F\"><u> Mailjet </ u></ span></ a></p>");
                    body.AppendLine("</div>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</tbody>");
                    body.AppendLine("</table>");
                    body.AppendLine("</div>");
                    body.AppendLine("<!--[if mso | IE]>");
                    body.AppendLine("</td>");
                    body.AppendLine("</tr>");
                    body.AppendLine("</table>");
                    body.AppendLine("<![endif]-->");
                    body.AppendLine("</div>");
                    body.AppendLine("</body>");
                    body.AppendLine("</html>");
                    break;
            }
            return body.ToString();
        }
    }
}